CREATE TABLE EMPLOYEE ( --WORKS
    EMP_ID INT PRIMARY KEY,
    EMP_FNAME VARCHAR(50) NOT NULL,
    EMP_LNAME VARCHAR(50) NOT NULL,
    EMP_ADDRESS VARCHAR(100),
    EMP_PHONE VARCHAR(15),
    EMP_DOB DATE,
    EMP_TITLE VARCHAR(50) NOT NULL,
    TYPE VARCHAR(20),
    MANAGER_ID INT,
    CONSTRAINT FK_EMPLOYEE_MANAGER
        FOREIGN KEY (MANAGER_ID)
        REFERENCES EMPLOYEE(EMP_ID)
);


CREATE TABLE JOB_TITLE ( --WORKS
    EMP_TITLE VARCHAR(50) PRIMARY KEY,
    JOB_DESC VARCHAR(255),
    JOB_SALARY DECIMAL(10, 2)
);

CREATE TABLE EMPLOYMENT_HISTORY_BRIDGE ( --WORKS
    EMP_ID INT,
    EMP_TITLE VARCHAR(50),
    START_DATE DATE,
    END_DATE DATE,
    SALARY DECIMAL(10, 2),
    PRIMARY KEY (EMP_ID, START_DATE),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    FOREIGN KEY (EMP_TITLE) REFERENCES JOB_TITLE (EMP_TITLE)
);

CREATE TABLE [SHIFT] (
  [SHIFT_ID] INT PRIMARY KEY,
  [SHIFT_START] DATETIME,
  [SHIFT_END] DATETIME,
  [BREAK] VARCHAR(50)
);


CREATE TABLE [CLOCK_IN] (
  [SHIFT_ID] INT,
  [EMP_NUM] INT,
  [CLOCK_IN_TIME] DATETIME,
  [CLOCK_OUT_TIME] DATETIME,
  PRIMARY KEY ([SHIFT_ID], [EMP_NUM]),
  FOREIGN KEY ([SHIFT_ID]) REFERENCES [SHIFT]([SHIFT_ID])
);


CREATE TABLE SALARY ( --WORKS
    EMP_ID INT PRIMARY KEY,
    BASE_SALARY DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);


CREATE TABLE WAGE ( --WORKS
    EMP_ID INT PRIMARY KEY,
    HOURLY_RATE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

--D TYPE RELATIONSHIP
CREATE TRIGGER trg_disjoint_salary_wage
ON SALARY
AFTER INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM WAGE WHERE WAGE.EMP_ID = (SELECT EMP_ID FROM inserted))
    BEGIN
        ROLLBACK;
        RAISERROR ('Employee already has a wage entry', 16, 1);
    END
END;
GO

CREATE TRIGGER trg_disjoint_wage_salary
ON WAGE
AFTER INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM SALARY WHERE SALARY.EMP_ID = (SELECT EMP_ID FROM inserted))
    BEGIN
        ROLLBACK;
        RAISERROR ('Employee already has a salary entry', 16, 1);
    END
END;
GO




CREATE TABLE [CHEF] (
  [EMP_ID] INT,
  PRIMARY KEY ([EMP_ID])
);