INSERT INTO EMPLOYEE (EMP_ID, EMP_FNAME, EMP_LNAME, EMP_ADDRESS, EMP_PHONE, EMP_TITLE) --WORKS
VALUES 
(101, 'Alice', 'Brown', '789 Pine St', '555-1010', 'Manager'),
(102, 'Bob', 'White', '321 Oak St', '555-2020', 'Chef');

INSERT INTO CHEF (EMP_ID)
VALUES 
(102); -- EMP_ID 102 for Bob, who is a Chef

INSERT INTO CHEF_CERT (CERT_ID, CERT_FEE, CERT_DATE_OFFER)
VALUES 
(1, 100.00, '2023-01-15'),
(2, 150.50, '2023-02-20'),
(3, 200.00, '2023-03-10'),
(4, 175.75, '2023-04-05');


INSERT INTO PROD_CATEGORY (PROD_CAT_ID, PROD_CAT_DESC) --WORKS
VALUES 
(1, 'Beverages'),
(2, 'Snacks');
-- Update Beverages to Pizza
UPDATE PROD_CATEGORY
SET PROD_CAT_DESC = 'Pizza'
WHERE PROD_CAT_DESC = 'Beverages';

-- Update Snacks to Pasta
UPDATE PROD_CATEGORY
SET PROD_CAT_DESC = 'Pasta'
WHERE PROD_CAT_DESC = 'Snacks';


INSERT INTO PROD_SUBCATEGORY (PROD_SUBCAT_ID, PROD_SUBCAT_DESC, PROD_CAT_ID) --WORKS
VALUES 
(1, 'Pizza', 1),
(2, 'Pasta', 2);

INSERT INTO PRODUCT (PROD_ID, PROD_PRICE, SERV_SIZE, PROD_SUBCAT_ID) --WORKS
VALUES 
(1, 1.50, 1, 1),
(2, 2.00, 1, 1),
(3, 3.00, 1, 2),
(4, 2.50, 1, 2);

INSERT INTO CUSTOMER (CUST_ID, CUST_FNAME, CUST_LNAME, CUST_ADDRESS, CUST_PHONE) --WORKS
VALUES 
(1, 'John', 'Doe', '123 Elm St', '555-1234'),
(2, 'Jane', 'Smith', '456 Maple Ave', '555-5678');

INSERT INTO [ORDER] (ORD_ID, CUST_ID, EMP_ID, ORD_DATE, ORD_TOTAL) --WORKS
VALUES 
(1, 1, 101, '2024-01-15', 5.50),
(2, 2, 102, '2024-01-20', 5.50);

INSERT INTO ORDER_DETAIL (ORD_DET_ID, ORD_ID, PROD_ID, ORD_PRICE) --WORKS
VALUES 
(1, 1, 1, 1.50),
(2, 1, 2, 2.00),
(3, 2, 3, 3.00),
(4, 2, 4, 2.50);

INSERT INTO STAGES (STAGE_ID, [DESC]) --WORKS
VALUES 
(1, 'Initial Stage'),
(2, 'Final Stage');

INSERT INTO ORDER_CURR_STAGE_BRIDGE (STAGE_ID, ORD_ID, DETAIL_ID) --WORKS
VALUES 
(1, 1, 1),
(2, 2, 3);

INSERT INTO VENDOR (VEND_ID, VEND_NAME, VEND_ADDRESS, VEND_PHONE) --WORKS
VALUES 
(1, 'Vendor A', '789 Oak St', '555-7890'),
(2, 'Vendor B', '101 Pine Rd', '555-1011');

INSERT INTO INVENTORY_CATEGORY (INV_CAT_ID, INV_CAT_DESC) --WORKS
VALUES 
(1, 'Food'),
(2, 'Drink');
-- Update Food to Pizza
UPDATE INVENTORY_CATEGORY
SET INV_CAT_DESC = 'Pizza'
WHERE INV_CAT_DESC = 'Food';

-- Update Drink to Pasta
UPDATE INVENTORY_CATEGORY
SET INV_CAT_DESC = 'Pasta'
WHERE INV_CAT_DESC = 'Drink';


INSERT INTO INVENTORY_SUBCATEGORY (INV_SUBCAT_ID, INV_SUBCAT_DESC, INV_CAT_ID) --WORKS
VALUES 
(1, 'Beverages', 2),
(2, 'Snacks', 1);
-- Update Beverages to Pizza
UPDATE INVENTORY_SUBCATEGORY
SET INV_SUBCAT_DESC = 'Pizza'
WHERE INV_SUBCAT_DESC = 'Beverages';

-- Update Snacks to Pasta
UPDATE INVENTORY_SUBCATEGORY
SET INV_SUBCAT_DESC = 'Pasta'
WHERE INV_SUBCAT_DESC = 'Snacks';


INSERT INTO INVENTORY (INV_ID, INV_QUANTITY_ON_HAND, INV_SUBCAT_ID, VEND_ID) --WORKS
VALUES 
(1, 100, 1, 1),
(2, 200, 2, 2);

INSERT INTO RECIPE_BRIDGE (PROD_ID, INV_ID, QTY_NEED) --WORKS
VALUES 
(1, 1, 10),
(2, 2, 20);

INSERT INTO PRICE_HISTORY (PROD_ID, START_DATE, END_DATE, PRICE) --WORKS
VALUES 
(1, '2024-01-01', '2024-06-30', 1.50),
(2, '2024-01-01', '2024-06-30', 2.00);

INSERT INTO PAYMENT (PYMT_ID, PYMT_METHOD, DISCOUNT_AMOUNT, ORD_ID) --WORKS
VALUES 
(1, 'Credit Card', 0.50, 1),
(2, 'Cash', 0.00, 2);

INSERT INTO MEMBERSHIP (MEMB_ID, CUST_ID, MEMB_POINTS) --WORKS
VALUES 
(1, 1, 100),
(2, 2, 200);

INSERT INTO RATING_BRIDGE (RATING_ID, CUST_ID, ORD_ID, STAR_RAT, COMMENTS) --WORKS
VALUES 
(1, 1, 1, 5, 'Excellent'),
(2, 2, 2, 4, 'Good');
