--Step 1
SELECT 
    C.PROD_CAT_DESC,
    SUM(D.ORD_PRICE) AS Total_Amount,
    SUM(DQ.Quantity_Sold) AS Total_Quantity
FROM 
    ORDER_DETAIL D
JOIN 
    PRODUCT P ON D.PROD_ID = P.PROD_ID
JOIN 
    PROD_SUBCATEGORY S ON P.PROD_SUBCAT_ID = S.PROD_SUBCAT_ID
JOIN 
    PROD_CATEGORY C ON S.PROD_CAT_ID = C.PROD_CAT_ID
JOIN
    (SELECT PROD_ID, COUNT(*) AS Quantity_Sold FROM ORDER_DETAIL GROUP BY PROD_ID) DQ ON DQ.PROD_ID = D.PROD_ID
GROUP BY 
    C.PROD_CAT_DESC;

--Step 2
SELECT 
    S.PROD_SUBCAT_DESC,
    SUM(D.ORD_PRICE) AS Total_Amount,
    SUM(DQ.Quantity_Sold) AS Total_Quantity
FROM 
    ORDER_DETAIL D
JOIN 
    PRODUCT P ON D.PROD_ID = P.PROD_ID
JOIN 
    PROD_SUBCATEGORY S ON P.PROD_SUBCAT_ID = S.PROD_SUBCAT_ID
JOIN
    (SELECT PROD_ID, COUNT(*) AS Quantity_Sold FROM ORDER_DETAIL GROUP BY PROD_ID) DQ ON DQ.PROD_ID = D.PROD_ID
GROUP BY 
    S.PROD_SUBCAT_DESC;

